2023-05-03 14:58:27,703 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-05-03 14:58:27,703 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Configure stats pid to 89476
2023-05-03 14:58:27,704 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Loading settings from /Users/wooseokhan/.config/wandb/settings
2023-05-03 14:58:27,704 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Loading settings from /Users/wooseokhan/Desktop/AI_intro/sentiment_analysis/wandb/settings
2023-05-03 14:58:27,704 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-03 14:58:27,704 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-03 14:58:27,704 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-03 14:58:27,704 ERROR   MainThread:89476 [wandb_setup.py:_flush():76] error
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1146, in init
    wi.setup(kwargs)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 289, in setup
    wandb_login._login(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 221, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 201, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 145, in prompt_api_key
    write_key(settings, key, api=api)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 244, in write_key
    api.clear_setting("anonymous", globally=True, persist=True)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 394, in clear_setting
    self._settings.clear(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/old/settings.py", line 71, in clear
    clear_setting(self._global_settings, Settings._global_path(), persist)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/old/settings.py", line 67, in clear_setting
    with open(settings_path, "w+") as f:
PermissionError: [Errno 13] Permission denied: '/Users/wooseokhan/.config/wandb/settings'
2023-05-03 14:58:27,706 ERROR   MainThread:89476 [wandb_setup.py:_flush():76] error
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1146, in init
    wi.setup(kwargs)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 289, in setup
    wandb_login._login(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 221, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 201, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 145, in prompt_api_key
    write_key(settings, key, api=api)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 244, in write_key
    api.clear_setting("anonymous", globally=True, persist=True)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 394, in clear_setting
    self._settings.clear(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/old/settings.py", line 71, in clear
    clear_setting(self._global_settings, Settings._global_path(), persist)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/old/settings.py", line 67, in clear_setting
    with open(settings_path, "w+") as f:
PermissionError: [Errno 13] Permission denied: '/Users/wooseokhan/.config/wandb/settings'
2023-05-03 14:58:27,706 ERROR   MainThread:89476 [wandb_setup.py:_flush():76] error
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1146, in init
    wi.setup(kwargs)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 289, in setup
    wandb_login._login(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 221, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 201, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 145, in prompt_api_key
    write_key(settings, key, api=api)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 244, in write_key
    api.clear_setting("anonymous", globally=True, persist=True)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 394, in clear_setting
    self._settings.clear(
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/old/settings.py", line 71, in clear
    clear_setting(self._global_settings, Settings._global_path(), persist)
  File "/opt/anaconda3/envs/sentiment_analysis/lib/python3.9/site-packages/wandb/old/settings.py", line 67, in clear_setting
    with open(settings_path, "w+") as f:
PermissionError: [Errno 13] Permission denied: '/Users/wooseokhan/.config/wandb/settings'
2023-05-03 14:58:27,707 INFO    MainThread:89476 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-05-03 14:58:27,707 INFO    MainThread:89476 [wandb_init.py:_log_setup():507] Logging user logs to /Users/wooseokhan/Desktop/AI_intro/sentiment_analysis/wandb/run-20230503_145827-v48bxbil/logs/debug.log
2023-05-03 14:58:27,707 INFO    MainThread:89476 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/wooseokhan/Desktop/AI_intro/sentiment_analysis/wandb/run-20230503_145827-v48bxbil/logs/debug-internal.log
2023-05-03 14:58:27,708 INFO    MainThread:89476 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb9f3321d60>
2023-05-03 14:58:27,710 INFO    MainThread:89476 [wandb_init.py:init():547] calling init triggers
2023-05-03 14:58:27,710 INFO    MainThread:89476 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-03 14:58:27,710 INFO    MainThread:89476 [wandb_init.py:init():596] starting backend
2023-05-03 14:58:27,710 INFO    MainThread:89476 [wandb_init.py:init():600] setting up manager
2023-05-03 14:58:27,722 INFO    MainThread:89476 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-05-03 14:58:27,734 INFO    MainThread:89476 [wandb_init.py:init():606] backend started and connected
2023-05-03 14:58:27,746 INFO    MainThread:89476 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-03 14:58:27,747 INFO    MainThread:89476 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-03 14:58:27,747 INFO    MainThread:89476 [wandb_init.py:init():700] updated telemetry
2023-05-03 14:58:27,818 INFO    MainThread:89476 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-03 14:58:29,372 INFO    MainThread:89476 [wandb_run.py:_on_init():2177] communicating current version
2023-05-03 14:58:30,701 INFO    MainThread:89476 [wandb_run.py:_on_init():2186] got version response 
2023-05-03 14:58:30,701 INFO    MainThread:89476 [wandb_init.py:init():787] starting run threads in backend
2023-05-03 14:58:33,582 INFO    MainThread:89476 [wandb_run.py:_console_start():2158] atexit reg
2023-05-03 14:58:33,584 INFO    MainThread:89476 [wandb_run.py:_redirect():2013] redirect: SettingsConsole.WRAP_RAW
2023-05-03 14:58:33,585 INFO    MainThread:89476 [wandb_run.py:_redirect():2078] Wrapping output streams.
2023-05-03 14:58:33,585 INFO    MainThread:89476 [wandb_run.py:_redirect():2103] Redirects installed.
2023-05-03 14:58:33,587 INFO    MainThread:89476 [wandb_init.py:init():829] run started, returning control to user process
